"use client"

import { FormEvent, useMemo, useState } from "react"
import { Search, ArrowRight, BookOpen, CalendarDays, GraduationCap, Newspaper, ClipboardCheck } from "lucide-react"
import Link from "next/link"

const searchablePages = [
  { title: "Academic Results", description: "PSLE and SFNA results with published source references.", href: "/results", icon: ClipboardCheck, terms: "results PSLE SFNA examination exam grades performance" },
  { title: "Admissions", description: "Application process, requirements and admissions guidance.", href: "/admissions", icon: GraduationCap, terms: "admission apply requirements enrollment" },
  { title: "Academics", description: "Academic approach, learning journey and school programmes.", href: "/academics", icon: BookOpen, terms: "academics curriculum learning subjects" },
  { title: "News & Events", description: "Verified school updates, announcements and events.", href: "/news", icon: Newspaper, terms: "news announcement events updates" },
  { title: "Academic Calendar", description: "Official dates and school activities.", href: "/calendar", icon: CalendarDays, terms: "calendar terms examinations dates" },
  { title: "Resources", description: "Forms, policies, prospectus and official downloads.", href: "/resources", icon: BookOpen, terms: "resources forms policies prospectus downloads" },
]

export default function SearchPage() {
  const [query, setQuery] = useState("")
  const results = useMemo(() => { const q = query.trim().toLowerCase(); if (!q) return searchablePages; return searchablePages.filter(p => `${p.title} ${p.description} ${p.terms}`.toLowerCase().includes(q)) }, [query])
  const submit = (event: FormEvent) => event.preventDefault()
  return <main className="min-h-screen bg-background pt-28"><section className="bg-school-dark py-16 text-white"><div className="mx-auto max-w-4xl px-4 text-center sm:px-6"><p className="mb-3 text-sm font-bold uppercase tracking-[0.2em] text-school-orange">Search</p><h1 className="text-4xl font-bold md:text-5xl">Find information on Sammena</h1><p className="mx-auto mt-4 max-w-2xl text-white/70">Search the public website for admissions, academics, resources, news and important dates.</p><form onSubmit={submit} className="mx-auto mt-8 flex max-w-2xl gap-2 rounded-2xl bg-white p-2"><Search className="ml-3 mt-3 h-5 w-5 shrink-0 text-slate-400"/><input aria-label="Search Sammena website" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search admissions, academics, resources..." className="min-w-0 flex-1 bg-transparent px-2 py-3 text-slate-900 outline-none"/><button type="submit" className="rounded-xl bg-[#c9a24b] px-5 py-3 font-bold text-[#071d3b]">Search</button></form></div></section><section className="mx-auto max-w-5xl px-4 py-14 sm:px-6"><div className="mb-6 flex items-center justify-between gap-4"><h2 className="text-xl font-bold">{query ? `${results.length} result${results.length === 1 ? "" : "s"}` : "Explore Sammena"}</h2>{query && <button type="button" onClick={()=>setQuery("")} className="text-sm font-semibold text-school-orange">Clear search</button>}</div><div className="grid gap-4 md:grid-cols-2">{results.map(({title,description,href,icon:Icon})=><Link key={href} href={href} className="group rounded-2xl border border-border bg-card p-6 shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><div className="flex items-start gap-4"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-school-orange/10"><Icon className="h-5 w-5 text-school-orange"/></div><div><h3 className="font-bold group-hover:text-school-orange">{title}</h3><p className="mt-1 text-sm leading-6 text-muted-foreground">{description}</p><span className="mt-3 inline-flex items-center gap-1 text-xs font-bold text-school-orange">Explore <ArrowRight className="h-3.5 w-3.5 transition-transform group-hover:translate-x-1"/></span></div></div></Link>)}</div>{results.length === 0 && <div className="rounded-2xl border border-dashed border-border p-10 text-center"><p className="font-semibold">No matching public page found.</p><p className="mt-2 text-sm text-muted-foreground">Try a broader term such as admissions, academics, calendar or resources.</p></div>}</section></main>
}
