"use client"
import { useEffect,useState } from "react"
import Link from "next/link"
import { ArrowLeft, CheckCircle2, Database, RefreshCw, ShieldCheck } from "lucide-react"
type State={role:string;schoolId:string|null;database:boolean;cms:boolean;calendar:boolean;audit:boolean;sessionMode:string;secretsExposed:boolean}
export default function AdminSettings(){
 const [data,setData]=useState<State|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null)
 const load=async():Promise<void>=>{setLoading(true);setError(null);try{const r=await fetch("/api/admin/settings",{cache:"no-store"}),p=await r.json().catch(():null=>null);if(r.status===401||r.status===403||r.status===503){window.location.assign("/login?type=admin&returnTo=/admin/settings");return}if(!r.ok)throw new Error(p?.error?.message??"System status unavailable.");setData(p.data)}catch(e){setError(e instanceof Error?e.message:"System status unavailable.")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[])
 return <main className="min-h-screen bg-[#f6f4ef] text-[#172033]"><header className="bg-[#102846] text-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 sm:px-8"><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-[#d7c28e]">Sammena Administration</p><h1 className="text-lg font-bold">System settings</h1></div><Link href="/admin" className="inline-flex items-center gap-2 text-sm font-semibold text-white/80"><ArrowLeft className="h-4 w-4"/>Admin</Link></div></header><div className="mx-auto max-w-5xl px-5 py-8 sm:px-8"><div className="border-b border-slate-200 pb-6"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#a27e35]">Production integrity</p><h2 className="mt-2 text-3xl font-bold text-[#17365d]">System configuration</h2><p className="mt-2 text-sm leading-7 text-slate-600">Read-only operational checks. Credentials and secrets are never rendered into the browser.</p></div>{loading?<div className="py-16 text-center"><RefreshCw className="mx-auto h-6 w-6 animate-spin text-[#b9964f]"/></div>:error?<div className="mt-7 border border-red-200 bg-white p-6 text-sm text-red-700">{error}</div>:data&&<><section className="mt-7 grid gap-4 sm:grid-cols-2"><Status label="Database connection" ok={data.database}/><Status label="CMS storage" ok={data.cms}/><Status label="Calendar storage" ok={data.calendar}/><Status label="Audit storage" ok={data.audit}/></section><section className="mt-6 border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><Database className="h-5 w-5 text-[#a27e35]"/><h3 className="font-bold text-[#17365d]">Runtime identity</h3></div><dl className="mt-6 grid gap-5 sm:grid-cols-2"><div><dt className="text-xs font-bold uppercase tracking-wider text-slate-400">Role</dt><dd className="mt-1 font-semibold">{data.role.replaceAll("_"," ")}</dd></div><div><dt className="text-xs font-bold uppercase tracking-wider text-slate-400">School scope</dt><dd className="mt-1 font-mono text-xs">{data.schoolId??"Not configured"}</dd></div><div><dt className="text-xs font-bold uppercase tracking-wider text-slate-400">Session</dt><dd className="mt-1 font-semibold">{data.sessionMode}</dd></div><div><dt className="text-xs font-bold uppercase tracking-wider text-slate-400">Browser secrets</dt><dd className="mt-1 font-semibold">{data.secretsExposed?"Exposed":"Not exposed"}</dd></div></dl></section><div className="mt-6 flex items-start gap-3 border border-[#d9c28a] bg-[#fffdf6] p-5"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0 text-[#8c6c28]"/><p className="text-sm leading-6 text-slate-600">Administrative writes remain permission-protected and school-scoped. Environment credentials are server-only.</p></div></>}</div></main>
}
function Status({label,ok}:{label:string;ok:boolean}){return <div className="flex items-center justify-between border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><CheckCircle2 className={ok?"h-5 w-5 text-emerald-600":"h-5 w-5 text-red-600"}/><span className="text-sm font-semibold">{label}</span></div><span className={ok?"text-xs font-bold uppercase text-emerald-700":"text-xs font-bold uppercase text-red-700"}>{ok?"Connected":"Unavailable"}</span></div>}
