import { Navbar } from "@/components/navbar"
import { Footer } from "@/components/footer"
import Link from "next/link"
import { ClipboardList, FileText, CheckCircle, UserCheck, GraduationCap, Phone, ArrowRight, AlertCircle, MessageCircle } from "lucide-react"

const steps = [
  ["01", ClipboardList, "Enquire", "Contact the school or visit the campus to confirm availability, requirements and the appropriate entry level."],
  ["02", FileText, "Apply", "Complete the official application process and provide the required supporting documents."],
  ["03", CheckCircle, "Assessment", "Where applicable, the pupil completes an age-appropriate assessment to support correct placement."],
  ["04", UserCheck, "Review", "The school reviews the application and discusses relevant educational considerations."],
  ["05", GraduationCap, "Enroll", "Successful applicants complete registration, fee arrangements and final enrollment."],
] as const

const prePrimaryRequirements = ["Completed application form", "Birth certificate or equivalent identification", "Recent passport photographs", "Relevant health or immunisation records where required", "Parent/guardian identification"]
const primaryRequirements = ["Completed application form", "Birth certificate or equivalent identification", "Recent passport photographs", "Previous school academic records where applicable", "Transfer documentation where applicable", "Parent/guardian identification"]

const faqs = [
  ["When should I apply?", "Contact the school early so you can confirm available places, entry requirements and the current enrollment timetable."],
  ["What ages and classes are available?", "Admissions depend on the child's age, previous schooling and available places. Contact the school for current entry-level guidance."],
  ["Is an assessment required?", "An assessment may be used where appropriate to help determine class placement and understand the pupil's learning needs."],
  ["What if I do not have every document?", "Contact the school and explain the situation so the admissions team can advise you on the appropriate next step."],
  ["How can I contact admissions?", "Use the telephone contact below or visit the Contact page to send an enquiry."],
] as const

export default function AdmissionsPage() {
  return <main className="min-h-screen"><Navbar />
    <section className="pt-32 pb-16 bg-school-dark text-white"><div className="max-w-7xl mx-auto px-4 text-center sm:px-6 lg:px-8"><span className="text-school-gold font-semibold text-sm uppercase tracking-wider">Admissions</span><h1 className="text-4xl md:text-5xl font-bold mt-2 mb-4">A Clear Path to Enrollment</h1><p className="text-white/65 text-lg max-w-2xl mx-auto leading-relaxed">Everything families need to understand the admissions journey, prepare documents and contact the school.</p><div className="flex flex-col sm:flex-row justify-center gap-4 mt-8"><Link href="/admissions/apply" className="inline-flex items-center justify-center gap-2 px-7 py-3.5 bg-school-gold text-school-dark font-bold rounded-xl hover:opacity-90">Start Application <ArrowRight className="w-4 h-4" /></Link><a href="tel:+255750227073" className="inline-flex items-center justify-center gap-2 px-7 py-3.5 border border-white/20 rounded-xl font-semibold"><Phone className="w-4 h-4" /> Call Admissions</a></div></div></section>
    <section className="py-20 bg-background"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="text-center mb-14"><span className="text-school-gold font-semibold text-sm uppercase tracking-wider">The Journey</span><h2 className="text-3xl md:text-4xl font-bold mt-2">Admissions Process</h2><p className="text-muted-foreground mt-3">A simple process designed to help families know what happens next.</p></div><div className="grid md:grid-cols-3 lg:grid-cols-5 gap-8">{steps.map(([num, Icon, title, description]) => <div key={num} className="text-center"><div className="mx-auto w-16 h-16 rounded-full bg-school-dark border-4 border-school-gold flex items-center justify-center mb-4"><Icon className="w-6 h-6 text-school-gold" /></div><div className="text-school-gold font-bold text-xs tracking-widest">STEP {num}</div><h3 className="font-semibold mt-1 mb-2">{title}</h3><p className="text-muted-foreground text-xs leading-relaxed">{description}</p></div>)}</div></div></section>
    <section className="py-20 bg-school-neutral"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="text-center mb-12"><span className="text-school-gold font-semibold text-sm uppercase tracking-wider">Prepare Early</span><h2 className="text-3xl md:text-4xl font-bold mt-2">Admission Requirements</h2></div><div className="grid md:grid-cols-2 gap-8">{[["Pre-Primary", "Early years entry", prePrimaryRequirements], ["Primary School", "Standards 1–7", primaryRequirements]].map(([title, subtitle, items]) => <div key={title as string} className="bg-card rounded-2xl p-7 border border-border shadow-sm"><div className="flex items-center gap-3 mb-5"><div className="w-10 h-10 rounded-xl bg-school-gold/15 flex items-center justify-center"><GraduationCap className="w-5 h-5 text-school-gold" /></div><div><h3 className="font-bold">{title as string}</h3><p className="text-muted-foreground text-xs">{subtitle as string}</p></div></div><ul className="space-y-3">{(items as string[]).map(req => <li key={req} className="flex items-start gap-2.5"><CheckCircle className="w-4 h-4 text-school-gold shrink-0 mt-0.5" /><span className="text-muted-foreground text-sm">{req}</span></li>)}</ul></div>)}</div><div className="mt-5 flex items-start gap-2.5 bg-school-gold/10 border border-school-gold/20 rounded-xl px-5 py-4"><AlertCircle className="w-4 h-4 text-school-gold shrink-0 mt-0.5" /><p className="text-sm text-foreground/70">Requirements and availability can change. Confirm current requirements directly with the school before making arrangements.</p></div><div className="mt-8 flex justify-center"><Link href="/contact" className="inline-flex items-center gap-2 px-6 py-3 bg-school-dark text-white font-semibold rounded-xl"><MessageCircle className="w-4 h-4" /> Ask Admissions</Link></div></div></section>
    <section className="py-20 bg-school-dark text-white"><div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8"><div className="text-center mb-12"><span className="text-school-gold font-semibold text-sm uppercase tracking-wider">Common Questions</span><h2 className="text-3xl font-bold mt-2">Frequently Asked Questions</h2></div><div className="space-y-3">{faqs.map(([q, a]) => <details key={q} className="group bg-white/5 rounded-2xl border border-white/10"><summary className="cursor-pointer list-none p-5 font-semibold flex items-center justify-between gap-4">{q}<span className="text-school-gold text-xl group-open:rotate-45 transition-transform">+</span></summary><p className="px-5 pb-5 text-white/60 text-sm leading-relaxed">{a}</p></details>)}</div></div></section>
    <section className="py-16 bg-school-gold"><div className="max-w-4xl mx-auto px-4 text-center sm:px-6 lg:px-8"><h2 className="text-2xl md:text-3xl font-bold text-school-dark mb-3">Ready to Begin?</h2><p className="text-school-dark/75 mb-7">Speak with the school before submitting documents or making enrollment arrangements.</p><div className="flex flex-col sm:flex-row justify-center gap-4"><Link href="/admissions/apply" className="inline-flex items-center justify-center gap-2 px-6 py-3 bg-school-dark text-white font-semibold rounded-xl">Start Application <ArrowRight className="w-4 h-4" /></Link><Link href="/contact" className="inline-flex items-center justify-center gap-2 px-6 py-3 border-2 border-school-dark text-school-dark font-semibold rounded-xl"><MessageCircle className="w-4 h-4" /> Contact School</Link></div></div></section>
    <Footer /></main>
}
