"use client"

import { FormEvent, ReactNode, useEffect, useState } from "react"
import Link from "next/link"
import { ArrowLeft, ArrowRight, CheckCircle2, ClipboardList, FileText, GraduationCap, UserRound, CalendarDays, Save, RotateCcw, HeartPulse, Users } from "lucide-react"

const steps = ["Guardian", "Learner", "Home & School", "Review"]
const draftKey = "sammena-admission-draft-v2"
const makeReference = () => `SAM-${new Date().getFullYear()}-${Math.random().toString(36).slice(2, 8).toUpperCase()}`

type FormData = { guardian:string; phone:string; email:string; relationship:string; occupation:string; guardianNationality:string; address:string; learner:string; dob:string; age:string; gender:string; nationality:string; homeRegion:string; homeDistrict:string; division:string; village:string; eyeColor:string; height:string; weight:string; religion:string; tribe:string; entry:string; studyType:string; academicYear:string; previous:string; previousYear:string; medical:string; allergies:string; distance:string; preferredStart:string; siblings:string; photoReady:boolean }
const emptyForm:FormData = { guardian:"",phone:"",email:"",relationship:"",occupation:"",guardianNationality:"",address:"",learner:"",dob:"",age:"",gender:"",nationality:"",homeRegion:"",homeDistrict:"",division:"",village:"",eyeColor:"",height:"",weight:"",religion:"",tribe:"",entry:"",studyType:"Day",academicYear:"",previous:"",previousYear:"",medical:"",allergies:"",distance:"",preferredStart:"",siblings:"",photoReady:false }

export default function ApplyPage(){
 const [step,setStep]=useState(0),[submitted,setSubmitted]=useState(false),[saved,setSaved]=useState(false),[reference,setReference]=useState(""),[form,setForm]=useState<FormData>(emptyForm)
 useEffect(()=>{try{const raw=localStorage.getItem(draftKey);if(raw)setForm({...emptyForm,...JSON.parse(raw)})}catch{}}
 ,[])
 const update=(key:keyof FormData,value:string|boolean)=>{setSaved(false);setForm(p=>({...p,[key]:value}))}
 const saveDraft=()=>{try{localStorage.setItem(draftKey,JSON.stringify(form));setSaved(true)}catch{}}
 const clearDraft=()=>{localStorage.removeItem(draftKey);setForm(emptyForm);setStep(0);setSaved(false)}
 const next=(e:FormEvent)=>{e.preventDefault();if(step<3)setStep(step+1);else{setReference(makeReference());localStorage.removeItem(draftKey);setSubmitted(true)}}
 if(submitted)return <main className="min-h-screen bg-school-neutral px-4 py-16"><div className="mx-auto max-w-xl rounded-3xl border border-border bg-card p-8 text-center shadow-xl md:p-12"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-school-gold/15"><CheckCircle2 className="h-8 w-8 text-school-gold"/></div><p className="mt-6 text-xs font-bold uppercase tracking-[0.2em] text-school-gold">Application prepared</p><h1 className="mt-2 text-3xl font-bold">Thank you, {form.guardian||"Parent / Guardian"}</h1><div className="mt-5 rounded-2xl bg-school-neutral p-5 text-left text-sm"><p><strong>Application reference:</strong> {reference}</p><p className="mt-2"><strong>Learner:</strong> {form.learner||"Not provided"}</p><p className="mt-2"><strong>Class:</strong> {form.entry||"Not provided"}</p><p className="mt-2"><strong>Study type:</strong> {form.studyType}</p></div><p className="mt-4 text-sm leading-6 text-muted-foreground">This is a prepared application reference for the current browser session. Live submission, document upload and server-side tracking require the secure admissions backend.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row sm:justify-center"><Link href="/admissions" className="rounded-xl bg-school-dark px-5 py-3 text-sm font-semibold text-white">Back to Admissions</Link><Link href="/" className="rounded-xl border border-border px-5 py-3 text-sm font-semibold">Home</Link></div></div></main>
 return <main className="min-h-screen bg-school-neutral px-4 py-10 md:py-16"><div className="mx-auto max-w-5xl"><div className="flex flex-wrap items-center justify-between gap-3"><Link href="/admissions" className="inline-flex items-center gap-2 text-sm font-semibold text-school-dark"><ArrowLeft className="h-4 w-4"/> Admissions</Link><div className="flex items-center gap-2"><button type="button" onClick={saveDraft} className="inline-flex items-center gap-2 rounded-xl border border-border bg-card px-3 py-2 text-xs font-semibold"><Save className="h-4 w-4"/>{saved?"Draft saved":"Save draft"}</button><button type="button" onClick={clearDraft} className="inline-flex items-center gap-2 rounded-xl border border-border bg-card px-3 py-2 text-xs font-semibold text-muted-foreground"><RotateCcw className="h-4 w-4"/> Clear</button></div></div><div className="mt-8 overflow-hidden rounded-3xl border border-border bg-card shadow-xl"><div className="bg-school-dark p-8 text-white md:p-10"><p className="text-xs font-bold uppercase tracking-[0.2em] text-school-gold">Sammena Admissions</p><h1 className="mt-2 text-3xl font-bold md:text-4xl">Complete Admission Application</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-white/65">The digital application now follows the information structure in the Sammena joining instruction, including learner profile, family details, placement, health information and study type.</p></div><div className="grid border-b border-border md:grid-cols-4">{steps.map((label,i)=><div key={label} className={`border-b-2 p-4 text-center text-xs font-bold ${i===step?"border-school-gold text-school-gold":"border-transparent text-muted-foreground"}`}><span className="mr-2">0{i+1}</span>{label}</div>)}</div><form onSubmit={next} className="p-7 md:p-10">
 {step===0&&<Section icon={Users} title="Parent / Guardian details" text="Information required to identify and contact the responsible parent or guardian."><div className="grid gap-5 md:grid-cols-2"><Field label="Full name" value={form.guardian} onChange={v=>update("guardian",v)} required/><Field label="Phone" type="tel" value={form.phone} onChange={v=>update("phone",v)} required/><Field label="Email" type="email" value={form.email} onChange={v=>update("email",v)}/><Select label="Relationship" value={form.relationship} onChange={v=>update("relationship",v)} options={["Parent","Guardian","Other authorized caregiver"]} required/><Field label="Occupation" value={form.occupation} onChange={v=>update("occupation",v)}/><Field label="Guardian nationality" value={form.guardianNationality} onChange={v=>update("guardianNationality",v)}/><Field label="Address" value={form.address} onChange={v=>update("address",v)}/></div></Section>}
 {step===1&&<Section icon={GraduationCap} title="Learner profile" text="The joining instruction requests these learner particulars."><div className="grid gap-5 md:grid-cols-2"><Field label="Pupil / learner full name" value={form.learner} onChange={v=>update("learner",v)} required/><Field label="Date of birth" type="date" value={form.dob} onChange={v=>update("dob",v)} required/><Field label="Age" value={form.age} onChange={v=>update("age",v)}/><Select label="Gender" value={form.gender} onChange={v=>update("gender",v)} options={["Male","Female"]} required/><Field label="Nationality" value={form.nationality} onChange={v=>update("nationality",v)}/><Field label="Home region" value={form.homeRegion} onChange={v=>update("homeRegion",v)}/><Field label="Home district" value={form.homeDistrict} onChange={v=>update("homeDistrict",v)}/><Field label="Division" value={form.division} onChange={v=>update("division",v)}/><Field label="Village / Street" value={form.village} onChange={v=>update("village",v)}/><Field label="Eye color" value={form.eyeColor} onChange={v=>update("eyeColor",v)}/><Field label="Height" placeholder="e.g. cm" value={form.height} onChange={v=>update("height",v)}/><Field label="Mass / weight" placeholder="e.g. kg" value={form.weight} onChange={v=>update("weight",v)}/><Field label="Religion (if required by school)" value={form.religion} onChange={v=>update("religion",v)}/><Field label="Tribe (if required by school)" value={form.tribe} onChange={v=>update("tribe",v)}/></div></Section>}
 {step===2&&<Section icon={ClipboardList} title="Placement, home & wellbeing" text="Admission, study type, previous school and welfare information."><div className="grid gap-5 md:grid-cols-2"><Select label="Admission applied for" value={form.entry} onChange={v=>update("entry",v)} options={["Pre-Unity","Class I","Class II","Class III","Class IV","Class V","Class VI","Class VII"]} required/><Select label="Type of studies" value={form.studyType} onChange={v=>update("studyType",v)} options={["Day","Boarding"]} required/><Field label="Academic year" value={form.academicYear} onChange={v=>update("academicYear",v)} required/><Field label="Last school attended" value={form.previous} onChange={v=>update("previous",v)}/><Field label="Year attended" value={form.previousYear} onChange={v=>update("previousYear",v)}/><Field label="Distance home to school" placeholder="e.g. km" value={form.distance} onChange={v=>update("distance",v)}/><Field label="Preferred start date" type="date" value={form.preferredStart} onChange={v=>update("preferredStart",v)}/><Field label="Siblings currently at Sammena" value={form.siblings} onChange={v=>update("siblings",v)}/><TextArea label="Special / medical attention" value={form.medical} onChange={v=>update("medical",v)}/><TextArea label="Allergies" value={form.allergies} onChange={v=>update("allergies",v)}/><div className="rounded-2xl border border-school-gold/20 bg-school-gold/10 p-4 text-sm text-muted-foreground md:col-span-2"><div className="flex items-start gap-3"><HeartPulse className="mt-0.5 h-5 w-5 shrink-0 text-school-gold"/><p>Health information is based on the supplied joining instruction. Production handling should use secure access controls and appropriate privacy safeguards.</p></div></div><label className="flex items-start gap-3 rounded-2xl border border-border p-4 text-sm md:col-span-2"><input type="checkbox" checked={form.photoReady} onChange={e=>update("photoReady",e.target.checked)} className="mt-1"/><span><strong>Student photo</strong><br/><span className="text-muted-foreground">Confirm that a passport-size/student photo will be supplied. Actual upload will be connected to the secure document service.</span></span></label></div></Section>}
 {step===3&&<Section icon={FileText} title="Review application" text="Review the information before preparing the application."><div className="grid gap-3 rounded-2xl bg-school-neutral p-5 text-sm md:grid-cols-2"><Review label="Guardian" value={form.guardian}/><Review label="Phone" value={form.phone}/><Review label="Relationship" value={form.relationship}/><Review label="Occupation" value={form.occupation}/><Review label="Learner" value={form.learner}/><Review label="DOB / Age" value={`${form.dob||"Not provided"} / ${form.age||"Not provided"}`}/><Review label="Gender" value={form.gender}/><Review label="Nationality" value={form.nationality}/><Review label="Home" value={[form.homeRegion,form.homeDistrict,form.division,form.village].filter(Boolean).join(", ")}/><Review label="Applied for" value={form.entry}/><Review label="Study type" value={form.studyType}/><Review label="Academic year" value={form.academicYear}/><Review label="Previous school" value={form.previous}/><Review label="Medical attention" value={form.medical}/><Review label="Allergies" value={form.allergies}/><Review label="Photo" value={form.photoReady?"To be supplied":"Not confirmed"}/></div><p className="mt-5 text-xs leading-5 text-muted-foreground">The supplied joining instruction also contains school rules, attendance expectations, payment procedures, fee schedules, boarding requirements and office approvals. Those should become separate digital workflows rather than cluttering the learner intake form.</p></Section>}
 <div className="mt-9 flex items-center justify-between gap-3 border-t border-border pt-6"><button type="button" onClick={()=>setStep(Math.max(0,step-1))} disabled={step===0} className="inline-flex items-center gap-2 rounded-xl border border-border px-5 py-3 text-sm font-semibold disabled:opacity-40"><ArrowLeft className="h-4 w-4"/> Back</button><button type="submit" className="inline-flex items-center gap-2 rounded-xl bg-school-dark px-6 py-3 text-sm font-bold text-white">{step===3?"Prepare Application":"Continue"}<ArrowRight className="h-4 w-4"/></button></div></form></div></div></main>
}
function Section({icon:Icon,title,text,children}:{icon:typeof Users;title:string;text:string;children:ReactNode}){return <div><div className="mb-7 flex gap-4"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-school-gold/15"><Icon className="h-5 w-5 text-school-gold"/></div><div><h2 className="text-xl font-bold">{title}</h2><p className="mt-1 text-sm text-muted-foreground">{text}</p></div></div>{children}</div>}
function Field({label,value,onChange,type="text",required=false,placeholder=""}:{label:string;value:string;onChange:(v:string)=>void;type?:string;required?:boolean;placeholder?:string}){return <label className="text-sm font-semibold">{label}{required&&<span className="text-school-gold"> *</span>}<input type={type} value={value} placeholder={placeholder} onChange={e=>onChange(e.target.value)} required={required} className="mt-2 w-full rounded-xl border border-border bg-background px-4 py-3 font-normal outline-none focus:ring-2 focus:ring-school-gold"/></label>}
function TextArea({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="text-sm font-semibold md:col-span-2">{label}<textarea value={value} onChange={e=>onChange(e.target.value)} rows={3} className="mt-2 w-full rounded-xl border border-border bg-background px-4 py-3 font-normal outline-none focus:ring-2 focus:ring-school-gold"/></label>}
function Select({label,value,onChange,options,required=false}:{label:string;value:string;onChange:(v:string)=>void;options:string[];required?:boolean}){return <label className="text-sm font-semibold">{label}{required&&<span className="text-school-gold"> *</span>}<select value={value} onChange={e=>onChange(e.target.value)} required={required} className="mt-2 w-full rounded-xl border border-border bg-background px-4 py-3 font-normal outline-none focus:ring-2 focus:ring-school-gold"><option value="">Select {label.toLowerCase()}</option>{options.map(o=><option key={o}>{o}</option>)}</select></label>}
function Review({label,value}:{label:string;value:string}){return <div className="flex flex-col gap-1 border-b border-border/70 pb-3 last:border-0 sm:flex-row sm:justify-between"><span className="font-semibold">{label}</span><span className="text-muted-foreground sm:max-w-[65%] sm:text-right">{value||"Not provided"}</span></div>}
