"use client"
import { useEffect, useState } from "react"
import { Navbar } from "@/components/navbar"
import { Footer } from "@/components/footer"
import Image from "next/image"
import { X, ZoomIn, ArrowRight, Images, Sparkles } from "lucide-react"
import { cn } from "@/lib/utils"
import { useScrollAnimation } from "@/hooks/use-scroll-animation"
const categories=["All","Events","Classes","Activities","Sports"]
const galleryItems=[{src:"/images/gallery-1.jpg",alt:"Students competing during sports day athletics event",title:"Sports Day 2023",category:"Sports",span:"lg:row-span-2"},{src:"/images/gallery-2.jpg",alt:"Students doing chemistry experiments in the school lab",title:"Science Lab Session",category:"Classes",span:""},{src:"/images/gallery-3.jpg",alt:"Students celebrating graduation ceremony",title:"Graduation Ceremony 2023",category:"Events",span:""},{src:"/images/gallery-4.jpg",alt:"Students learning in the ICT computer lab",title:"ICT Computer Lab",category:"Classes",span:""},{src:"/images/gallery-5.jpg",alt:"Students performing in cultural day event",title:"Cultural Day Performance",category:"Events",span:""},{src:"/images/gallery-6.jpg",alt:"Students studying in the school library",title:"School Library",category:"Activities",span:""}]
function Reveal({children,className,delay=0}:{children:React.ReactNode;className?:string;delay?:number}){const{ref,isVisible}=useScrollAnimation();return <div ref={ref} data-motion="section" data-visible={isVisible?"true":"false"} className={cn(className)} style={{transitionDelay:`${delay}ms`}}>{children}</div>}
export default function GalleryPage(){const[activeCategory,setActiveCategory]=useState("All");const[lightbox,setLightbox]=useState<null|typeof galleryItems[0]>(null);const filtered=galleryItems.filter(item=>activeCategory==="All"||item.category===activeCategory);useEffect(()=>{if(!lightbox)return;const onKey=(e:KeyboardEvent)=>{if(e.key==="Escape")setLightbox(null)};document.addEventListener("keydown",onKey);document.body.style.overflow="hidden";return()=>{document.removeEventListener("keydown",onKey);document.body.style.overflow=""}},[lightbox]);return <main className="min-h-screen overflow-x-hidden"><Navbar/>
<section className="relative isolate overflow-hidden bg-school-dark pb-20 pt-36 text-white"><div className="absolute inset-0 bg-[radial-gradient(circle_at_30%_0%,rgba(216,181,91,.18),transparent_45%),radial-gradient(circle_at_80%_70%,rgba(18,63,115,.5),transparent_40%)]"/><div className="relative mx-auto max-w-7xl px-5 text-center sm:px-6 lg:px-8"><Reveal><div className="mx-auto flex w-fit items-center gap-2 rounded-full border border-school-gold/30 bg-white/5 px-4 py-2 text-xs font-bold uppercase tracking-[0.2em] text-school-gold"><Images className="h-4 w-4"/>Our Life in Pictures</div><h1 className="mt-6 text-4xl font-bold tracking-tight md:text-6xl">School Gallery</h1><p className="mx-auto mt-5 max-w-2xl text-lg leading-8 text-white/65">A glimpse into the vibrant life at Sammena School — from the classroom to the sports field, every moment tells a story of growth and excellence.</p></Reveal></div></section>
<section className="bg-background py-20 lg:py-28"><div className="mx-auto max-w-7xl px-5 sm:px-6 lg:px-8"><Reveal className="mb-10 flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><span className="text-school-orange font-semibold text-sm uppercase tracking-[0.2em]">Explore School Life</span><h2 className="mt-2 text-3xl font-bold text-foreground md:text-4xl">Moments that matter.</h2></div><div className="flex flex-wrap gap-2">{categories.map(cat=><button key={cat} onClick={()=>setActiveCategory(cat)} className={cn("rounded-full px-4 py-2 text-sm font-semibold transition-all duration-300",activeCategory===cat?"-translate-y-0.5 bg-school-dark text-white shadow-lg":"bg-school-neutral text-foreground/65 hover:-translate-y-0.5 hover:bg-school-dark/10")}>{cat}</button>)}</div></Reveal><div className="grid auto-rows-[220px] gap-4 sm:grid-cols-2 lg:grid-cols-3">{filtered.map((item,index)=><Reveal key={item.src} delay={index*70} className={item.span}><button type="button" data-motion="card" className="group relative h-full w-full overflow-hidden rounded-3xl bg-school-dark text-left shadow-md focus:outline-none focus-visible:ring-2 focus-visible:ring-school-gold" onClick={()=>setLightbox(item)} aria-label={`Open ${item.title}`}><Image src={item.src} alt={item.alt} fill sizes="(max-width: 640px) 100vw, (max-width: 1024px) 50vw, 33vw" className="object-cover transition-transform duration-1000 ease-out group-hover:scale-110"/><div className="absolute inset-0 bg-gradient-to-t from-black/85 via-black/10 to-transparent opacity-70 transition-opacity duration-500 group-hover:opacity-90"/><div className="absolute inset-0 flex items-center justify-center"><span className="flex h-12 w-12 scale-75 items-center justify-center rounded-full border border-white/20 bg-black/25 text-white opacity-0 backdrop-blur-md transition-all duration-500 group-hover:scale-100 group-hover:opacity-100"><ZoomIn className="h-5 w-5"/></span></div><div className="absolute bottom-0 left-0 right-0 p-5 translate-y-2 transition-transform duration-500 group-hover:translate-y-0"><span className="text-school-orange text-xs font-bold uppercase tracking-[0.18em]">{item.category}</span><p className="mt-1 text-lg font-bold text-white">{item.title}</p><span className="mt-2 inline-flex items-center gap-1 text-xs font-semibold text-white/0 transition-colors duration-300 group-hover:text-white/70">View moment <ArrowRight className="h-3.5 w-3.5"/></span></div></button></Reveal>)}</div>{filtered.length===0&&<div className="py-20 text-center text-muted-foreground">No photos in this category yet. Check back soon!</div>}</div></section>
<section className="bg-school-neutral py-16"><Reveal className="mx-auto max-w-4xl px-5 text-center sm:px-6"><div className="mx-auto flex h-12 w-12 items-center justify-center rounded-2xl bg-school-orange/10 text-school-orange"><Sparkles className="h-5 w-5"/></div><h2 className="mt-5 text-2xl font-bold text-foreground md:text-3xl">Every school day becomes a story.</h2><p className="mx-auto mt-3 max-w-2xl leading-7 text-muted-foreground">Explore the people, learning and experiences that make Sammena a community.</p></Reveal></section>
{lightbox&&<div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/95 p-4 backdrop-blur-sm" role="dialog" aria-modal="true" aria-label={lightbox.title} onClick={()=>setLightbox(null)}><button className="absolute right-5 top-5 z-10 flex h-11 w-11 items-center justify-center rounded-full border border-white/10 bg-white/10 text-white transition-all duration-300 hover:scale-105 hover:bg-white/20" onClick={()=>setLightbox(null)} aria-label="Close gallery"><X className="h-5 w-5"/></button><div className="w-full max-w-5xl overflow-hidden rounded-3xl shadow-2xl" onClick={e=>e.stopPropagation()}><div className="relative aspect-video bg-black"><Image src={lightbox.src} alt={lightbox.alt} fill sizes="90vw" className="object-contain" priority/></div><div className="bg-school-dark px-6 py-5"><span className="text-school-orange text-xs font-bold uppercase tracking-[0.18em]">{lightbox.category}</span><p className="mt-1 text-lg font-bold text-white">{lightbox.title}</p></div></div></div>}<Footer/></main>}
