"use client"

import { useMemo, useState } from "react"
import Link from "next/link"
import { Activity, ArrowRight, BookOpen, CalendarDays, CheckCircle2, ClipboardCheck, GraduationCap, Library, MessageSquareText, ShieldCheck, TrendingUp, Users } from "lucide-react"

const students = [
  { name: "Amani M.", className: "Standard VII", attendance: 96, average: 82, status: "On track" },
  { name: "Neema K.", className: "Standard VI", attendance: 91, average: 78, status: "On track" },
  { name: "Baraka P.", className: "Standard IV", attendance: 87, average: 68, status: "Needs support" },
]

const actions = [
  { label: "Mark attendance", icon: CheckCircle2, href: "#attendance" },
  { label: "Enter assessment", icon: ClipboardCheck, href: "#assessment" },
  { label: "Open library", icon: Library, href: "#library" },
  { label: "Quality review", icon: ShieldCheck, href: "/quality" },
]

export default function PortalPage() {
  const [view, setView] = useState<"overview" | "students" | "quality">("overview")
  const [term, setTerm] = useState("Term II · 2026")
  const schoolStats = useMemo(() => [
    { label: "Students", value: "188", detail: "27 Pre-primary · 23 Std I", icon: Users },
    { label: "Attendance", value: "94.3%", detail: "+2.1% vs last month", icon: Activity },
    { label: "Academic average", value: "76.8%", detail: "+4.4% vs previous term", icon: TrendingUp },
    { label: "Open QA actions", value: "7", detail: "3 due this month", icon: ShieldCheck },
  ], [])
  return (
    <main className="min-h-screen bg-[#f5f6f7] text-slate-800">
      <div className="border-b border-[#0a3158]/20 bg-[#06203b] text-white"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4 px-5 py-3 sm:px-8"><div><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-[#e2c46c]">Sammena Schools</p><p className="mt-1 text-sm font-semibold">School Portal</p></div><Link href="/" className="text-xs font-semibold text-white/75 hover:text-white">Back to website</Link></div></div>
      <div className="mx-auto max-w-7xl px-5 py-8 sm:px-8 lg:py-10">
        <header className="flex flex-col gap-5 border-b border-slate-200 pb-7 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#9b7728]">Management workspace</p><h1 className="mt-2 text-3xl font-bold tracking-tight text-[#0a3158] sm:text-4xl">School performance centre</h1><p className="mt-3 max-w-2xl text-sm leading-7 text-slate-600">A Sammena-built operational layer for student records, attendance, assessment, resources and school quality improvement.</p></div><div className="flex flex-wrap gap-2">{["overview", "students", "quality"].map(item => <button key={item} type="button" onClick={() => setView(item as typeof view)} className={`rounded-full px-4 py-2 text-xs font-bold capitalize transition ${view === item ? "bg-[#0a3158] text-white" : "border border-slate-200 bg-white text-slate-600 hover:border-[#9b7728]"}`}>{item}</button>)}<select value={term} onChange={e => setTerm(e.target.value)} className="rounded-full border border-slate-200 bg-white px-4 py-2 text-xs font-bold text-[#0a3158] outline-none focus:ring-2 focus:ring-[#c8a64b]"><option>Term I · 2026</option><option>Term II · 2026</option><option>Term III · 2026</option></select></div></header>
        <section className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4" aria-label="School KPIs">{schoolStats.map(({ label, value, detail, icon: Icon }) => <article key={label} className="border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><div className="rounded-xl bg-[#f4ecd6] p-2.5 text-[#8a6a24]"><Icon className="h-5 w-5" /></div><span className="text-[10px] font-bold uppercase tracking-[0.14em] text-slate-400">{term.split(" · ")[0]}</span></div><p className="mt-5 text-sm font-semibold text-slate-500">{label}</p><p className="mt-1 text-3xl font-bold text-[#0a3158]">{value}</p><p className="mt-2 text-xs text-slate-500">{detail}</p></article>)}</section>
        <section className="mt-7 grid gap-6 lg:grid-cols-[1.35fr_.65fr]"><div className="border border-slate-200 bg-white p-6" id="attendance"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#9b7728]">Attendance</p><h2 className="mt-2 text-xl font-bold text-[#0a3158]">Daily attendance pulse</h2></div><CalendarDays className="h-5 w-5 text-[#9b7728]" /></div><div className="mt-7 grid gap-5 sm:grid-cols-3">{[{label:"Present",value:177,percent:94.1},{label:"Absent",value:8,percent:4.3},{label:"Late",value:3,percent:1.6}].map(item => <div key={item.label}><div className="flex items-end justify-between"><span className="text-sm font-semibold text-slate-600">{item.label}</span><span className="text-2xl font-bold text-[#0a3158]">{item.value}</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-[#0a3158]" style={{ width: `${item.percent}%` }} /></div><p className="mt-2 text-xs text-slate-400">{item.percent}% of enrolled learners</p></div>)}</div></div><aside className="border border-slate-200 bg-[#0a3158] p-6 text-white"><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#e2c46c]">Quick actions</p><div className="mt-5 space-y-2">{actions.map(({label,icon:Icon,href}) => <Link key={label} href={href} className="flex items-center justify-between border border-white/10 bg-white/[.04] px-4 py-3 text-sm font-semibold hover:bg-white/[.09]"><span className="flex items-center gap-3"><Icon className="h-4 w-4 text-[#e2c46c]" />{label}</span><ArrowRight className="h-4 w-4 text-white/50" /></Link>)}</div></aside></section>
        {view !== "quality" && <section className="mt-6 border border-slate-200 bg-white p-6" id="assessment"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#9b7728]">Student progress</p><h2 className="mt-2 text-xl font-bold text-[#0a3158]">Learners needing attention first</h2></div><Link href="#students" className="text-sm font-bold text-[#8a6a24]">View student records <ArrowRight className="ml-1 inline h-4 w-4" /></Link></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[640px] text-left text-sm"><thead className="border-y border-slate-200 bg-[#f7f7f5] text-xs uppercase tracking-[0.12em] text-slate-500"><tr><th className="px-4 py-3">Learner</th><th className="px-4 py-3">Class</th><th className="px-4 py-3">Attendance</th><th className="px-4 py-3">Average</th><th className="px-4 py-3">Status</th></tr></thead><tbody>{students.map(student => <tr key={student.name} className="border-b border-slate-100"><td className="px-4 py-4 font-semibold text-[#0a3158]">{student.name}</td><td className="px-4 py-4 text-slate-500">{student.className}</td><td className="px-4 py-4">{student.attendance}%</td><td className="px-4 py-4 font-semibold">{student.average}%</td><td className="px-4 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${student.status === "On track" ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-700"}`}>{student.status}</span></td></tr>)}</tbody></table></div></section>}
        {view !== "students" && <section className="mt-6 grid gap-6 md:grid-cols-2" id="library"><article className="border border-slate-200 bg-white p-6"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#9b7728]">Learning resources</p><h2 className="mt-2 text-xl font-bold text-[#0a3158]">Textbook & library pulse</h2></div><BookOpen className="h-5 w-5 text-[#9b7728]" /></div><div className="mt-6 grid grid-cols-3 gap-3 text-center"><div className="bg-[#f7f7f5] p-4"><p className="text-2xl font-bold text-[#0a3158]">612</p><p className="mt-1 text-[11px] text-slate-500">Books</p></div><div className="bg-[#f7f7f5] p-4"><p className="text-2xl font-bold text-[#0a3158]">87%</p><p className="mt-1 text-[11px] text-slate-500">Available</p></div><div className="bg-[#f7f7f5] p-4"><p className="text-2xl font-bold text-[#0a3158]">31</p><p className="mt-1 text-[11px] text-slate-500">Issued</p></div></div></article><article className="border border-slate-200 bg-white p-6"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#9b7728]">Communication</p><h2 className="mt-2 text-xl font-bold text-[#0a3158]">Family communication</h2></div><MessageSquareText className="h-5 w-5 text-[#9b7728]" /></div><p className="mt-4 text-sm leading-7 text-slate-600">Keep notices, attendance alerts, academic updates and school messages in one auditable communication stream.</p><button type="button" className="mt-5 inline-flex items-center gap-2 bg-[#0a3158] px-4 py-3 text-sm font-bold text-white hover:bg-[#06203b]">Open message centre <ArrowRight className="h-4 w-4" /></button></article></section>}
        {view === "quality" && <section className="mt-6 border border-slate-200 bg-white p-6"><div className="flex items-center gap-3"><ShieldCheck className="h-6 w-6 text-[#9b7728]" /><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#9b7728]">Quality management</p><h2 className="mt-1 text-xl font-bold text-[#0a3158]">Sammena quality workspace</h2></div></div><p className="mt-4 max-w-3xl text-sm leading-7 text-slate-600">Track school self-assessment, evidence, findings and improvement actions using a Sammena workflow inspired by school quality assurance practice.</p><Link href="/quality" className="mt-5 inline-flex items-center gap-2 font-bold text-[#8a6a24]">Open quality workspace <ArrowRight className="h-4 w-4" /></Link></section>}
        <footer className="mt-8 flex flex-col gap-3 border-t border-slate-200 pt-5 text-xs text-slate-500 sm:flex-row sm:items-center sm:justify-between"><span>Internal prototype data · Replace with authenticated school records before production use.</span><span className="flex items-center gap-1.5"><GraduationCap className="h-3.5 w-3.5" /> Sammena School Portal</span></footer>
      </div>
    </main>
  )
}
