import Link from "next/link"
import { ArrowRight, GraduationCap, Users, ShieldCheck, LockKeyhole, LayoutDashboard, BellRing } from "lucide-react"

const portals = [
  [Users,"Parent Portal","Fees, attendance, results, announcements and school communication."],
  [GraduationCap,"Student Portal","Learning resources, timetable, results and student services."],
  [ShieldCheck,"Staff Portal","Staff services and secure access to school systems."],
] as const

export default function PortalPage() {
  return <main className="min-h-screen bg-background pt-28"><section className="border-b border-border bg-school-dark py-16 text-white"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><p className="mb-3 text-sm font-bold uppercase tracking-[0.2em] text-school-gold">Digital Services</p><h1 className="text-4xl font-bold md:text-5xl">Sammena Family Hub</h1><p className="mt-5 max-w-2xl text-white/70">One secure front door for future parent, student and staff digital services.</p></div></section><section className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><div className="grid gap-6 md:grid-cols-3">{portals.map(([Icon,title,text])=><div key={title} className="rounded-2xl border border-border bg-card p-7 shadow-sm hover-lift"><div className="flex h-12 w-12 items-center justify-center rounded-xl bg-school-gold/15"><Icon className="h-6 w-6 text-school-gold"/></div><h2 className="mt-5 text-xl font-bold">{title}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p><button type="button" disabled className="mt-6 inline-flex items-center gap-2 rounded-xl border border-border px-4 py-2.5 text-sm font-semibold text-muted-foreground">Secure access <LockKeyhole className="h-4 w-4"/></button></div>)}</div><div className="mt-12 grid gap-5 md:grid-cols-3"><Feature icon={LayoutDashboard} title="One family view" text="A future unified experience can connect school services without exposing internal systems publicly."/><Feature icon={BellRing} title="Important updates" text="Parents can eventually receive school announcements and time-sensitive notifications in one place."/><Feature icon={LockKeyhole} title="Security first" text="Authentication, permissions, audit logs and privacy controls belong in the secure SIS layer."/></div><div className="mt-10 rounded-2xl border border-dashed border-border bg-school-neutral p-8 text-center"><p className="font-semibold">Portal authentication is not live yet.</p><p className="mt-2 text-sm text-muted-foreground">The public gateway is ready. Live access should be connected only after the Sammena SIS backend, authentication and security controls are verified.</p><Link href="/contact" className="mt-5 inline-flex items-center gap-2 font-semibold text-school-dark">Contact the school <ArrowRight className="h-4 w-4"/></Link></div></section></main>
}
function Feature({icon:Icon,title,text}:{icon:typeof LockKeyhole;title:string;text:string}) { return <div className="rounded-2xl border border-border bg-card p-6"><Icon className="h-6 w-6 text-school-gold"/><h3 className="mt-4 font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p></div> }
