"use client"

import { useEffect, useState } from "react"
import Link from "next/link"
import { ArrowLeft, RefreshCw, ShieldCheck } from "lucide-react"

type AuditEvent = { id:string; action:string; entity_type:string; entity_id:string|null; request_id:string|null; created_at:string }

export default function AdminAuditPage() {
  const [events,setEvents]=useState<AuditEvent[]>([])
  const [loading,setLoading]=useState(true)
  const [error,setError]=useState<string|null>(null)
  const load=async(): Promise<void>=>{setLoading(true);setError(null);try{const r=await fetch("/api/admin/audit",{cache:"no-store"});const p=await r.json().catch((): null => null);if(r.status===401||r.status===403||r.status===503){window.location.assign("/login?type=admin&returnTo=/admin/audit");return}if(!r.ok)throw new Error(p?.error?.message??"Audit log unavailable.");setEvents(p.data??[])}catch(e){setError(e instanceof Error?e.message:"Audit log unavailable.")}finally{setLoading(false)}}
  useEffect((): void => { void load() }, [])
  return <main className="min-h-screen bg-[#f6f4ef] text-[#172033]"><header className="bg-[#102846] text-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 sm:px-8"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-full bg-white/10"><ShieldCheck className="h-5 w-5 text-[#d7c28e]"/></div><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-[#d7c28e]">Sammena Administration</p><h1 className="text-lg font-bold">Audit log</h1></div></div><Link href="/admin" className="inline-flex items-center gap-2 text-sm font-semibold text-white/80 hover:text-white"><ArrowLeft className="h-4 w-4"/>Admin</Link></div></header><div className="mx-auto max-w-7xl px-5 py-8 sm:px-8"><div className="flex items-end justify-between border-b border-slate-200 pb-6"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#a27e35]">Privileged activity</p><h2 className="mt-2 text-3xl font-bold text-[#17365d]">Recent audit events</h2><p className="mt-2 text-sm text-slate-600">Server-recorded administrative actions. Latest 100 events are shown.</p></div><button onClick={()=>void load()} className="inline-flex items-center gap-2 border border-slate-200 bg-white px-4 py-3 text-sm font-bold text-[#17365d]"><RefreshCw className="h-4 w-4"/>Refresh</button></div>{loading?<div className="py-20 text-center"><RefreshCw className="mx-auto h-6 w-6 animate-spin text-[#b9964f]"/></div>:error?<div className="mt-7 border border-red-200 bg-white p-6 text-sm text-red-700">{error}</div>:<div className="mt-7 overflow-hidden border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-[#f7f5ef] text-xs uppercase tracking-wider text-slate-500"><tr><th className="px-5 py-4">Time</th><th className="px-5 py-4">Action</th><th className="px-5 py-4">Entity</th><th className="px-5 py-4">Entity ID</th><th className="px-5 py-4">Request</th></tr></thead><tbody className="divide-y divide-slate-100">{events.map(e=><tr key={e.id} className="hover:bg-[#fbfaf7]"><td className="whitespace-nowrap px-5 py-4 text-slate-500">{new Date(e.created_at).toLocaleString()}</td><td className="px-5 py-4 font-semibold text-[#17365d]">{e.action}</td><td className="px-5 py-4 text-slate-600">{e.entity_type}</td><td className="px-5 py-4 font-mono text-xs text-slate-500">{e.entity_id??"—"}</td><td className="px-5 py-4 font-mono text-xs text-slate-400">{e.request_id??"—"}</td></tr>)}</tbody></table></div>{events.length===0&&<p className="p-10 text-center text-sm text-slate-500">No audit events have been recorded yet.</p>}</div>}</div></main>
}